### PR TITLE
Fix some English translation.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by levin108** [comment]
thanks, but sorry, you made some mistakes in the translation, I can't merge it.

**Comment by xuhdev** [comment]
Please point them out. Thanks.

**Comment by levin108** [comment]
-msgstr "添加联系人失败."
+msgstr "添加联系人"

-msgstr "更改照片失败."
+msgstr "更改照片"

-msgstr "请求名单失败."
+msgstr "请求名单错误."

**Comment by levin108** [comment]
-    const char intro[] = N_("Hybrid is a lightweight extensible IM framework,"
-    const char intro[] = N_("Hybrid is a lightweight extensible IM framework, "

Here I notified you only add a blankspace at the end, I don't think it's necessary.

And there're too much fuzzy in the po file.

**Comment by yuyichao** [comment]
And somehow .pot file isn't updated??

**Comment by xuhdev** [comment]
Weird, I didn't change Chinese chars. Shouldn't I modify po/zh_CN.po?

**Comment by yuyichao** [comment]
First, since you have changed those strings that are marked as translate, you should modify both po and pot file as well.
A rough update can be done using the message.sh (sth like that, too lazy to check file name). It will try to guess what need to be update.
Then you need to go through the updated po file (pot should be fine), and remove those "fuzzy"s and mistake made by the script.

I remember this was what I have done last time~~~. @levin108 may know more since he wrote that script (and I still haven't figured out what all of those arguments of that command mean.) ~~ =P

**Comment by yuyichao** [comment]
O yes, and finally, you'd better compile and check if all the translations u can see have been updated properly.~~

**Comment by xuhdev** [comment]
I understand. I'll repush soon.

**Comment by levin108** [comment]
I suggest we provide a more detailed log to tell what we did in the patch, every time we made a commit, we'd better give it a complete description, thanks :)

**Comment by yuyichao** [comment]
@levin108 LOL this is what u told me last time and is still what I am not good at.~

**Comment by levin108** [comment]
@yuyichao It's a good habit, try to do better next time you submit a patch, don't commit too many times, format a feature into a patch set, and every patch in the patch set needs detailed log. Maybe you can try "guilt", a very convenient tool.

**Comment by xuhdev** [comment]
@levin108  In English, `,`, `.`, `:`, etc. should be appended with a space. Or it is grammar error. You could try it in some grammar checker, such as Microsoft Word.

**Pull request closed without merging**
